# Generated by Django 4.2.6 on 2023-10-23 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('pedigree', models.CharField(max_length=100)),
                ('feeding', models.TextField(max_length=250)),
                ('health', models.TextField(max_length=250)),
                ('competitions', models.ManyToManyField(related_name='horses', to='stable_schedule.competition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='stable_schedule.horse')),
            ],
        ),
        migrations.CreateModel(
            name='HorseCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stable_schedule.competition')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stable_schedule.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_healthy', to='stable_schedule.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(max_length=250)),
                ('time_of_day', models.CharField(max_length=64)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_feeding', to='stable_schedule.horse')),
            ],
        ),
    ]
