# Generated by Django 4.2.6 on 2023-10-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='feeding',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='health',
        ),
    ]
